### ISSUE TITLE
Initial documentation framework (epic)

### ISSUE THREAD

**Issue by GNiklasch** [GNiklasch/GWO-glitch-visualization#1]
Epic: Create a basic documentation set that will guide visitors to this repo to further information sources.

- [x] Flesh out `README.md`
- [x] Installation instructions for local use
- [x] A note about the rationale and design drivers
- [x] A note about what data are and aren't (yet) available on [GWOSC](https://gwosc.org/) for us to work with (can be included in the former)
- [ ] Pointer(s) to a list of worked examples

Points to bear in mind:
- Material that is likely to be updated relatively frequently cannot live in the main branch in `doc/` since any update would trigger a cloud redeployment.
- A wiki may thus be appropriate.
- Zooniverse > [Gravity Spy](https://www.zooniverse.org/projects/zooniverse/gravity-spy/) > [Talk](https://www.zooniverse.org/projects/zooniverse/gravity-spy/talk/) is already available as a forum (Zooniverse account required for active participation), and worked examples are better discussed there.
