### ISSUE TITLE
Cloud integration environment (epic)

### ISSUE THREAD

**Issue by GNiklasch** [GNiklasch/GWO-glitch-visualization#4]
Epic: Prepare a (private) deployment to the Streamlit Community Cloud for pre-production integration testing:
- [x] set up a dedicated branch (locally & GitHub repo)
- [x] deploy from this branch
- [ ] followup with Streamlit (feature-request) re hibernation on demand or after less than 7 days without traffic (this will need to be tracked with a separate story here)

**Comment by GNiklasch** [comment]
Integration deployment has been spooled up.

Considering to drop the third item from the original task list and allow the int deployment to be used by others for public preprod testing (and as a fallback when prod happens to have an outage that doesn't affect the whole cloud).
